avoid error if xclip is not reachable
schiessle/shareLinkCreator pull request #27
Opened 2020-06-30 12:30 UTC by jee-r

2020-06-30 15:08 UTC, schiessle commented on shareLinkCreator
> +<<<<<<< HEAD
I'm sure this doesn't belong here ;)

2020-06-30 15:09 UTC, schiessle commented
Thanks for your contribution. Can you fix the problems mentioned above and rebase it on the latest master? Thanks a lot!

2020-06-30 15:11 UTC, schiessle requested changes

2020-06-30 15:11 UTC, schiessle commented on shareLinkCreator
> +=======
same here...

2020-06-30 15:11 UTC, schiessle commented on shareLinkCreator
> +>>>>>>> e63cb31... avoid error if xclip is not reachable
and here....

2020-06-30 21:09 UTC, jee-r commented
oops sorry i don't double check this one, thank you for reviewing my PR.
Maybe i should close this one and create a new it would be easier for me, i'm not really comfortable with rebase ..etc. 
i'm learning :)

2020-07-01 15:53 UTC, schiessle commented
>Maybe i should close this one and create a new it would be easier for me, i'm not really comfortable with rebase ..etc.
i'm learning :)

sure, that's also possible

2022-03-28 17:04 UTC, closed without merging